version: '3.3'
services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Etc/UTC
      - UMASK=002
    volumes:
      - /portainer/Files/AppData/Config/Sonarr:/config
      - /mnt/manshare:/data
      - /dev/rtc:/dev/rtc
    ports:
      - 8989:8989
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: Radarr
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Etc/UTC
      - UMASK=002
    volumes:
      - /portainer/Files/AppData/Config/Radarr:/config
      - /mnt/manshare:/data
    ports:
      - 7878:7878
    restart: unless-stopped

  bazarr:
    image: linuxserver/bazarr:latest
    container_name: Bazarr
    environment:
      - PUID=1000
      - PGID=100
      - TZ=Etc/UTC
      - UMASK=002
    volumes:
      - /portainer/Files/AppData/Config/Bazarr:/config
      - /mnt/manshare:/data
    ports:
      - 6767:6767
    restart: unless-stopped

  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=Etc/UTC
    volumes:
      - /portainer/Files/AppData/Config/Jellyseerr-New:/app/config
    ports:
      - 5055:5055
    restart: unless-stopped

  notifiarr:
    image: golift/notifiarr
    container_name: notifiarr
    volumes:
      - /portainer/Files/AppData/Config/notifiarr:/config
      - /var/run/utmp:/var/run/utmp
      - /etc/machine-id:/etc/machine-id
    ports:
      - 5454:5454
    mem_limit: 1g
    memswap_limit: 1g
    restart: unless-stopped