version: '3.3'
services:
  vpn:
    image: qmcgaw/gluetun:latest
    container_name: vpn_gluetun_nordvpn
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      - VPN_SERVICE_PROVIDER=nordvpn
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - SERVER_COUNTRIES=United States
      - SERVER_REGIONS=The Americas
      - SERVER_CATEGORIES=P2P
      - TZ=America/New_York
      - DNS_UPDATE_PERIOD=1h
    ports:
      - 8080:8080       # qbittorrent — webui
      - 9696:9696       # prowlarr — webui
      - 58261:58261     # qbittorrent — torrenting (TCP)
      - 58261:58261/udp # qbittorrent — torrenting (UDP)
      - 8989:8989       # sonarr — webui
      - 9191:9191       # sonarr-anime — webui
      - 6767:6767       # bazarr — webui
      - 7878:7878       # radarr — webui
      - 8787:8787       # readarr — webui (reserved)
      - 5055:5055       # jellyseerr — webui
      - 8191:8191       # flaresolverr — proxy
      - 5454:5454       # notifiarr — webui
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    restart: unless-stopped